In [1]:
import torch

In [6]:
x=torch.arange(12)
print(x)
x.shape
x.numel()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


12

In [7]:
X=x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [8]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.tensor([[1,2,3],[4,5,6]]).shape


torch.Size([2, 3])

In [13]:
x=torch.tensor([1,2,3])
y=torch.tensor([4.0,5,6])
x+y,x**y

(tensor([5., 7., 9.]), tensor([  1.,  32., 729.]))

In [18]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
print(X)
Y=torch.tensor([[2.0,0,4,1],[1,2,3,4],[4,3,2,1]])
print(Y)
torch.cat((X,Y),dim=0)
torch.cat((X,Y),dim=1)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 0., 4., 1.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  0.,  4.,  1.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [19]:
X==Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
X.sum()

tensor(66.)

In [21]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a+b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [24]:
#内存分配
before=id(Y)
Y=Y+X
id(Y)==before
#原地操作
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 2816903585520
id(Z): 2816903585520
