In [1]:
import torch

In [6]:
x=torch.arange(12)
print(x)
x.shape
x.numel()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


12

In [7]:
X=x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [8]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.tensor([[1,2,3],[4,5,6]]).shape


torch.Size([2, 3])

In [13]:
x=torch.tensor([1,2,3])
y=torch.tensor([4.0,5,6])
x+y,x**y

(tensor([5., 7., 9.]), tensor([  1.,  32., 729.]))

In [18]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
print(X)
Y=torch.tensor([[2.0,0,4,1],[1,2,3,4],[4,3,2,1]])
print(Y)
torch.cat((X,Y),dim=0)
torch.cat((X,Y),dim=1)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 0., 4., 1.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  0.,  4.,  1.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [19]:
X==Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
X.sum()

tensor(66.)

In [21]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a+b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [24]:
#内存分配
before=id(Y)
Y=Y+X
id(Y)==before
#原地操作
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 2816903585520
id(Z): 2816903585520


In [2]:
#数据预处理
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [3]:
import pandas as pd
data=pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [5]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean(numeric_only=True))
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [ ]:
inputs=pd.get_dummies(inputs,dummy_na=False)
inputs


NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [9]:
import torch
X,Y=torch.tensor(inputs.values,dtype=torch.float32),torch.tensor(outputs.values,dtype=torch.float32)
X

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.